require:
  - rubocop-performance
  - rubocop-rspec

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

Layout/ExtraSpacing:
  Exclude:
    - db/schema.rb

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 80

Metrics/BlockLength:
  ExcludedMethods:
    - DbSchema.describe
    - db.table
    - db.migrate
    - migration.run
    - Sequel.connect

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 18

Style/TrailingUnderscoreVariable:
  Enabled: false

Style/GuardClause:
  MinBodyLength: 2

Style/MultilineBlockChain:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Lint/AssignmentInCondition:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Performance/InefficientHashSearch:
  Exclude:
    - db/schema.rb

Lint/ShadowingOuterLocalVariable:
  Exclude:
    - db/schema.rb

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
